const CountryCode = {
  CountryCodes: [
    {
      label: "Costa Rica",
      value: "+506",
      code: "CR",
      codigoPais: "es-CR",
      currency: "CRC",
    },
    {
      label: "Guatemala",
      value: "+502",
      code: "GT",
      codigoPais: "es-GT",
      currency: "GTQ",
    },
    {
      label: "El Salvador",
      value: "+503",
      code: "SV",
      codigoPais: "es-SV",
      currency: "USD",
    },
    {
      label: "Honduras",
      value: "+504",
      code: "HN",
      codigoPais: "es-HN",
      currency: "HNL",
    },
    {
      label: "Nicaragua",
      value: "+505",
      code: "NI",
      codigoPais: "es-NI",
      currency: "NIO",
    },
    {
      label: "Panama",
      value: "+507",
      code: "PA",
      codigoPais: "es-PA",
      currency: "PAB",
    },
    {
      label: "Argentina",
      value: "+54",
      code: "AR",
      codigoPais: "es-AR",
      currency: "ARS",
    },
    {
      label: "Bolivia",
      value: "+591",
      code: "BO",
      codigoPais: "es-BO",
      currency: "BOB",
    },
    {
      label: "Chile",
      value: "+56",
      code: "CL",
      codigoPais: "es-CL",
      currency: "CLP",
    },
    {
      label: "Colombia",
      value: "+57",
      code: "CO",
      codigoPais: "es-CO",
      currency: "COP",
    },
    {
      label: "Cuba",
      value: "+53",
      code: "CU",
      codigoPais: "es-CU",
      currency: "CUP",
    },
    {
      label: "Ecuador",
      value: "+593",
      code: "EC",
      codigoPais: "es-EC",
      currency: "USD",
    },
    {
      label: "Mexico",
      value: "+52",
      code: "MX",
      codigoPais: "es-MX",
      currency: "MXN",
    },
    {
      label: "Paraguay",
      value: "+595",
      code: "PY",
      codigoPais: "es-PY",
      currency: "PYG",
    },
    {
      label: "Peru",
      value: "+51",
      code: "PE",
      codigoPais: "es-PE",
      currency: "PEN",
    },
    {
      label: "Puerto Rico",
      value: "+1939",
      code: "PR",
      codigoPais: "es-PR",
      currency: "USD",
    },
    {
      label: "Spain",
      value: "+34",
      code: "ES",
      codigoPais: "es-ES",
      currency: "EUR",
    },
    {
      label: "Uruguay",
      value: "+598",
      code: "UY",
      codigoPais: "es-UY",
      currency: "UYU",
    },
    {
      label: "Venezuela ",
      value: "+58 ",
      code: "VE ",
      codigoPais: "es-VE ",
      currency: "VES",
    },
  ],
};

export default CountryCode;
